version: "3"

services:
  frontend:
    image: nginx:1.15-alpine
    volumes:
      - "./develop/nginx/sites:/etc/nginx/conf.d"
      - "./frontend/public:/frontend"
    ports:
      - 80:80
    restart: always
